# -*- coding: utf-8 -*-
"""2026-09-04 — Submission Drill and Fix a Broken Notebook — Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/jasontpv/DS2002FA26/blob/main/notebooks/01-foundations/2026-09-04%20%E2%80%94%20Submission%20Drill%20and%20Fix%20a%20Broken%20Notebook%20%E2%80%94%20Lab.ipynb

# DS2002 · Submission Drill and Fix a Broken Notebook

**Lab — 2026-09-04 · Fall 2026**  

---

## Lab 02 — Submission Drill and Fix a Broken Notebook

You have inherited a notebook that does not run. This is the most common way you will meet other people's code, so it is worth practicing deliberately.

Seven cells below are broken. Five throw an error, and two return a wrong answer without complaining at all — those are the dangerous ones. Fix all seven, prove your fixes with assertions, then push through the full submit loop.

**Submit in Canvas:** repository link and notebook link.

### How to read an error before you fix it

Python's traceback is read **bottom up**. The last line names the exception and the problem; the line above it points at your code.

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
    print(greeting)
NameError: name 'greeting' is not defined
```

Four exceptions cover most of what you will hit this semester:

| Exception | Usually means |
|---|---|
| `NameError` | The variable was never created, or the cell that created it never ran |
| `TypeError` | You mixed types — text where a number belongs is the classic |
| `KeyError` | That column or dictionary key does not exist. Check spelling and case |
| `FileNotFoundError` | The path is wrong for *this* environment |

For each fix below, write one sentence in the markdown cell saying what was actually wrong. "It works now" is not a diagnosis.

### Bug 1 — a name that does not exist
"""

# TODO: fix so this prints a greeting
greeting = "hello"
print(greeting)

"""**What was wrong:** was not a string

### Bug 2 — text where a number belongs

This should print `30`. Note that `'10' + 20` and `'10' + '20'` fail in different ways — make sure you know which one you are looking at.
"""

# TODO: fix so total is the number 30
total = 10 + 20
print(total)

"""**What was wrong:** 10 was a string not an int

### Bug 3 — off the end of a list
"""

items = ['burger', 'poncho', 'hat']

# TODO: print the LAST item, and do it in a way that still works
#       if someone adds a fourth item tomorrow
print(items[-1])

"""**What was wrong:** not indexed correctly because lists start at 0, also backwards indexing is necessary for it to be dynamic

### Bug 4 — no error, wrong answer

This is supposed to be the average. It prints a number, and the number is wrong.
"""

nums = [2, 4, 6, 8]
average = sum(nums) / len(nums)
print('average:', average)

"""**What was wrong:** needs to divide by the number of items in the list.

### Bug 5 — a table that cannot exist
"""

import pandas as pd

df = pd.DataFrame({'item': ['a', 'b'], 'price': [1, 2]})
print(df)

"""**What was wrong:** the arrays were not the same length

### Bug 6 — the answer changes when you re-run it

Run the next cell three times and watch the total move. Then fix it using what you built Wednesday: leave the source data alone and derive a new column from it. Your fix must give the same total on every run.
"""

sales = pd.DataFrame({
    'game': ['NC State', 'Louisville'],
    'raw': [1450, 1610],
})

# TODO: rewrite these two lines so re-running cannot change the answer
sales['units'] = sales['raw'] * 1.05
print('total units:', round(sales['units'].sum(), 2))

# Proof — this must print the same number three times
for _ in range(3):
    sales['units'] = sales['raw'] * 1.05
    print('total units:', round(sales['units'].sum(), 2))
    pass

"""**What was wrong:** The raw and adjusted data was saved under the same variable name

### Bug 7 — a path from someone else's laptop

This notebook was written on a machine you do not have. Fix it with the pattern from Wednesday's studio: look for the file, and fall back to the inline sample so the notebook still runs for whoever opens it next.
"""

import os
from io import StringIO

SAMPLE = '''game,units\nNC State,1450\nLouisville,1610\n'''

# TODO: replace this with a lookup + fallback that works anywhere
if os.path.exists(SAMPLE):
    orders = pd.read_csv(SAMPLE)
else:
    orders = pd.read_csv(StringIO(SAMPLE))
orders

"""**What was wrong:** needed if statement fall back

### Part 8 — prove the fixes

Assertions are how you state what must be true. If one fails, the notebook stops and tells you which claim broke — much better than scrolling for a wrong number.

**TODO:** uncomment each line and make them all pass.
"""

assert isinstance(greeting, str) and greeting != ''
assert total == 30
assert items[-1] == 'hat'
assert average == 5
assert len(df) == 2
assert len(orders) >= 2
print('All checks passed.')

"""### Part 9 — the submit drill

This is the part that is actually being graded on process. Do it in order.

1. **Restart the kernel and Run All.** Zero errors, top to bottom.
2. Download the notebook and put it in your repo under `notebooks/01-foundations/`, named `2026-09-04 — Submission Drill and Fix a Broken Notebook — Lab.ipynb`.
3. Commit with a message that says what you did, then push.
4. Confirm on github.com that the file is there and opens.
5. Fill in the cell below and submit both links in Canvas.

**TODO:** fill in the four values and make the check pass.
"""

import re

repo_url = 'TODO: https://github.com/you/ds2002-fa26'
commit_sha = 'TODO: short hash of the commit with this notebook in it'
notebook_link = 'TODO: the Kaggle or Colab link to this notebook'
ran_restart_and_run_all = False   # TODO: set True after you actually do it

checks = {
    'repo URL is a github.com URL':
        repo_url.startswith('https://github.com/')
        and repo_url.count('/') >= 4,
    'commit hash looks like a hash':
        bool(re.fullmatch(r'[0-9a-f]{7,40}', commit_sha.strip())),
    'notebook link filled in':
        notebook_link.startswith('http'),
    'restarted and ran all':
        ran_restart_and_run_all is True,
}

for label, passed in checks.items():
    print('PASS' if passed else 'FAIL', '-', label)

print()
print('Ready to submit:', all(checks.values()))

"""### Write-up

Bugs 4 and 6 did not raise an error. In a few sentences: how would you catch that class of bug in a project where you do not already know the right answer? Name something concrete you could add to a notebook.

_your answer here_

### Stretch

Write a `check_orders(df)` function that raises a clear error if the frame is missing either expected column, has zero rows, or contains a negative value in `units`. Then call it on `orders`. This is the shape of validation you will want in both projects.
"""

# stretch