# -*- coding: utf-8 -*-
"""2026-10-02 — Normalize and Join Nested JSON — Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/jasontpv/DS2002FA26/blob/main/notebooks/04-json-apis/2026-10-02%20%E2%80%94%20Normalize%20and%20Join%20Nested%20JSON%20%E2%80%94%20Lab.ipynb

# DS2002 · Normalize and Join Nested JSON

**Lab — 2026-10-02 · Fall 2026**  

---

## Lab 06 — Normalize and Join Nested JSON

Two JSON payloads of the kind an API hands you. Flatten each, join them, and answer the questions.

Before you write anything, answer this for yourself: **what is one row of the table you are building?** Every argument you pass to `json_normalize` follows from that answer, and getting it wrong is the reason this lab takes people two hours instead of forty minutes.

One vendor in the orders is not in the vendor list. That is on purpose.
"""

orders_json = [
  {'order':1,'vendor_id':'V-01','lines':[{'item':'Cheeseburger','qty':2},{'item':'Soda','qty':1}]},
  {'order':2,'vendor_id':'V-10','lines':[{'item':'Foam Finger','qty':1}]},
  {'order':3,'vendor_id':'V-07','lines':[{'item':'Hot Dog','qty':3}]},
]
vendors_json = [
  {'vendor_id':'V-01','name':'Hoos Burgers','zone':'A'},
  {'vendor_id':'V-10','name':'Cav Merch','zone':'A'},
]

"""**One row of my result is one:** order

### Q1 — Flatten the orders to one row per line item.

Keep `order` and `vendor_id` on every row.

*Expected: 4 rows, and the quantities should sum to 7.*
"""

import pandas as pd
lines = pd.json_normalize(
    orders_json,
    record_path='lines',
    meta=['order', 'vendor_id']
)

assert len(lines) == 4
assert lines['qty'].sum() == 7

"""### Q2 — Join the vendor information on.

Left join, `indicator=True`. Report which vendor did not match and how many units are attached to it.
"""

vendors = pd.json_normalize(vendors_json)

joined = pd.merge(
    lines,
    vendors,
    on='vendor_id',
    how='left',
    indicator=True
)

joined

#vendor NaN is unmatched, there are 3 units attached to it.

"""### Q3 — Total quantity per vendor name.

Decide how the unmatched vendor appears in this table, and say why in a comment.
"""

joined['name'] = joined['name'].fillna('Unmatched Vendor')

vendor_totals = (
    joined.groupby('name', as_index=False)['qty']
    .sum()
)

vendor_totals
#here the unmatched vendor, populates as "Unmatched Vendor" because I named it that way.

"""### Q4 — Which zone sold the most items?

Careful: if the unmatched vendor has no zone, your zone totals will not add up to 7. State what your total is and where the difference went.
"""

zone_totals = (
    joined.groupby('zone', as_index=False)['qty']
    .sum()
    .sort_values('qty', ascending=False)
)

zone_totals
#The total i got is 4, this is because the unmatched vendor has no zone. so the difference of 3 belongs to the unmatvhd vendor.

"""### Q5 — Handle a ragged payload.

A second batch arrives and it is not uniform: one order has no `lines` key at all, and one line item is missing its `qty`.

**TODO:** flatten what you can without crashing, and produce a frame where a missing quantity is distinguishable from a quantity of zero. Do **not** use `fillna(0)`.
"""

ragged_json = [
    {'order': 4, 'vendor_id': 'V-01', 'lines': [{'item': 'Soda', 'qty': 2}]},
    {'order': 5, 'vendor_id': 'V-10'},                       # no lines at all
    {'order': 6, 'vendor_id': 'V-01', 'lines': [{'item': 'Fries'}]},  # no qty
]

ragged_lines = []

for order in ragged_json:
    if 'lines' in order:
        for line in order['lines']:
            row = line.copy()
            row['order'] = order['order']
            row['vendor_id'] = order['vendor_id']
            ragged_lines.append(row)

ragged = pd.DataFrame(ragged_lines)

ragged

"""### Q6 — Validate"""

# assert len(lines) == 4
# assert lines['qty'].sum() == 7
# assert len(joined) == len(lines), 'the vendor join changed the row count'
print('checks passed.')

"""### Write-up

**a)** Why is "one row per line item" the useful shape here? What question becomes easy that would be hard with one row per order?

**b)** In Q5, what is the practical difference between a missing quantity and a quantity of zero, and what breaks downstream if you conflate them?

A. One row per line item is useful here because the orders can be analyzed on a by item basis easily. grouping and finding item sums is much easier this way.

B. Missing quantity data means that it is not known or not available how much the quantity is.  A quantity of 0 means that the quantity is known to be 0.
"""